# Labels for backend changes
"area:backend":
  - changed-files:
      - any-glob-to-any-file: "backend/**/*"

# Labels for frontend changes
"area:frontend":
  - changed-files:
      - any-glob-to-any-file: "frontend/**/*"

# Labels for CI/CD or GitHub Actions
"area:ci":
  - changed-files:
      - any-glob-to-any-file: ".github/**/*"

# Labels for documentation changes
"area:docs":
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - "LICENSE"
